services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env.development.db
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$${POSTGRES_USER}", "-d", "$${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  back:
    image: ${DOCKERHUB_USERNAME}/todo-back:${APP_VERSION}
    restart: unless-stopped
    environment:
      APP_VERSION: ${APP_VERSION}
    env_file:
      - .env.development.back
    ports:
      - 13000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app-config:/app/config:ro

  front:
    image: ${DOCKERHUB_USERNAME}/todo-front:${APP_VERSION}
    restart: unless-stopped
    env_file:
      - .env.development.front
    ports:
      - 18080:80
    depends_on:
      back:
        condition: service_started

volumes:
  pgdata:
