name: CI/CD Pipeline
 
on:
  push:
    branches: [week4]
 
jobs:
  checks:
    uses: ./.github/workflows/typecheck.yaml

  build:
    needs: [checks]
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  deploy:
    needs: [build]
    strategy:
      matrix:
        service: [back, front]
    uses: ./.github/workflows/deploy.yaml
    with:
      service_name: ${{ matrix.service }}
    secrets: inherit

  verify:
    needs: [deploy]
    uses: ./.github/workflows/verify.yaml
    secrets: inherit

  # notify:
  #   needs: [checks, build, deploy]
  #   if: always()
  #   uses: ./.github/workflows/notify.yml
  #   with:
  #     checks_result: ${{ needs.checks.result }}
  #     build_result: ${{ needs.build.result }}
  #     deploy_result: ${{ needs.deploy.result }}
  #   secrets:
  #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}