name: CI/CD Pipeline
 
on:
  workflow_dispatch:
  # push:
  #   branches: [week5]
 
jobs:
  checks:
    uses: ./.github/workflows/typecheck.yaml

  build:
    needs: [checks]
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit

  verify:
    needs: [deploy]
    uses: ./.github/workflows/verify.yaml
    secrets: inherit

  notify:
    needs: [checks, build, deploy, verify]
    if: always()
    uses: ./.github/workflows/notify.yaml
    with:
      checks_result: ${{ needs.checks.result }}
      build_result: ${{ needs.build.result }}
      deploy_result: ${{ needs.deploy.result }}
      verify_result: ${{ needs.verify.result }}
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}